use std::collections::HashMap;

use serde::Deserialize;

#[derive(Deserialize, Debug, Default, Clone)]
struct Arcade {
    coins: Option<usize>,
    dive_best_score_party: Option<usize>,
    dive_total_score_party: Option<usize>,
    lawn_moower_best_score_party: Option<usize>,
    lawn_moower_total_score_party: Option<usize>,
    minecart_racing_best_time_party: Option<usize>,
    minecart_racing_round_wins_party: Option<usize>,
    round_wins_party: Option<usize>,
    rpg_16_kills_best_score_party: Option<usize>,
    rpg_16_kills_party: Option<usize>,
    total_stars_party: Option<usize>,
    hider_wins_hide_and_seek: Option<usize>,
    prop_hunt_hider_wins_hide_and_seek: Option<usize>,
    jigsaw_rush_best_time_party: Option<usize>,
    jigsaw_rush_round_wins_party: Option<usize>,
    jungle_jump_best_time_party: Option<usize>,
    jungle_jump_round_wins_party: Option<usize>,
    lab_escape_best_time_party: Option<usize>,
    lab_escape_round_wins_party: Option<usize>,
    shooting_range_round_wins_party: Option<usize>,
    spider_maze_best_time_party: Option<usize>,
    spider_maze_round_wins_party: Option<usize>,
    the_floor_is_lava_best_time_party: Option<usize>,
    wins_party_count: Option<usize>,
    rounds_simon_says: Option<usize>,
    round_wins_simon_says: Option<usize>,
    top_score_simon_says: Option<usize>,
    pixel_party: Option<usize>,
    animal_slaughter_best_score_party: Option<usize>,
    animal_slaughter_kills_party: Option<usize>,
    animal_slaughter_round_wins_party: Option<usize>,
    anvil_spleef_best_time_party: Option<usize>,
    anvil_spleef_round_wins_party: Option<usize>,
    bombardment_best_time_party: Option<usize>,
    pixel_party_music_volume: Option<usize>,
    trampolinio_round_wins_party: Option<usize>,
    workshop_round_wins_party: Option<usize>,
    cannon_painting_round_wins_party: Option<usize>,
    the_floor_is_lava_round_wins_party: Option<usize>,
    volcano_round_wins_party: Option<usize>,
    fire_leapers_round_wins_party: Option<usize>,
    high_ground_best_score_party: Option<usize>,
    high_ground_total_score_party: Option<usize>,
    chicken_rings_best_time_party: Option<usize>,
    chicken_rings_round_wins_party: Option<usize>,
    hoe_hoe_hoe_best_score_party: Option<usize>,
    hoe_hoe_hoe_total_score_party: Option<usize>,
    lawn_moower_round_wins_party: Option<usize>,
    pig_fishing_round_wins_party: Option<usize>,
    showinfobook: Option<bool>,
    dropper: Option<Dropper>,
    last_tourney_ad: Option<usize>,
    bombardment_round_wins_party: Option<usize>,
    dive_round_wins_party: Option<usize>,
    frozen_floor_round_wins_party: Option<usize>,
    super_sheep_round_wins_party: Option<usize>,
    bow_kills_farm_hunt: Option<usize>,
    hunter_bow_kills_farm_hunt: Option<usize>,
    hunter_kills_farm_hunt: Option<usize>,
    hunters_bow_kills_farm_hunt: Option<usize>,
    kills_farm_hunt: Option<usize>,
    poop_collected_farm_hunt: Option<usize>,
    safe_taunts_used_farm_hunt: Option<usize>,
    taunts_used_farm_hunt: Option<usize>,
    hunter_wins_farm_hunt: Option<usize>,
    wins_farm_hunt: Option<usize>,
    high_ground_round_wins_party: Option<usize>,
    basic_zombie_kills_zombies: Option<usize>,
    best_round_zombies: Option<usize>,
    best_round_zombies_deadend: Option<usize>,
    best_round_zombies_deadend_normal: Option<usize>,
    bullets_hit_zombies: Option<usize>,
    bullets_shot_zombies: Option<usize>,
    deaths_zombies: Option<usize>,
    deaths_zombies_deadend: Option<usize>,
    deaths_zombies_deadend_normal: Option<usize>,
    doors_opened_zombies: Option<usize>,
    doors_opened_zombies_deadend: Option<usize>,
    doors_opened_zombies_deadend_normal: Option<usize>,
    empowered_zombie_kills_zombies: Option<usize>,
    fastest_time_10_zombies: Option<usize>,
    fastest_time_10_zombies_deadend_normal: Option<usize>,
    fire_zombie_kills_zombies: Option<usize>,
    headshots_zombies: Option<usize>,
    magma_zombie_kills_zombies: Option<usize>,
    pig_zombie_zombie_kills_zombies: Option<usize>,
    times_knocked_down_zombies: Option<usize>,
    times_knocked_down_zombies_deadend: Option<usize>,
    times_knocked_down_zombies_deadend_normal: Option<usize>,
    tnt_baby_zombie_kills_zombies: Option<usize>,
    total_rounds_survived_zombies: Option<usize>,
    total_rounds_survived_zombies_deadend: Option<usize>,
    total_rounds_survived_zombies_deadend_normal: Option<usize>,
    windows_repaired_zombies: Option<usize>,
    windows_repaired_zombies_deadend: Option<usize>,
    windows_repaired_zombies_deadend_normal: Option<usize>,
    wolf_zombie_kills_zombies: Option<usize>,
    zombie_kills_zombies: Option<usize>,
    zombie_kills_zombies_deadend: Option<usize>,
    zombie_kills_zombies_deadend_normal: Option<usize>,
    hitw_record_q: Option<usize>,
    rounds_hole_in_the_wall: Option<usize>,
    pig_jousting_round_wins_party: Option<usize>,
    #[serde(rename = "zombies_hideTutorials")]
    zombies_hide_tutorials: Option<bool>,
    #[serde(rename = "miniwalls_activeKit")]
    miniwalls_active_kit: Option<String>,
    miniwalls_inventory_layout: Option<HashMap<String, usize>>,
    deaths_throw_out: Option<usize>,
    kills_throw_out: Option<usize>,
    stamp_level: Option<usize>,
}

#[derive(Deserialize, Debug, Default, Clone)]
struct PixelParty {
    games_played: Option<usize>,
    games_played_normal: Option<usize>,
    highest_round: Option<usize>,
    rounds_completed: Option<usize>,
    rounds_completed_normal: Option<usize>,
    wins: Option<usize>,
    wins_normal: Option<usize>,
    games_played_hyper: Option<usize>,
    power_ups_collected: Option<usize>,
    power_ups_collected_hyper: Option<usize>,
    rounds_completed_hyper: Option<usize>,
    wins_hyper: Option<usize>,
}

#[derive(Deserialize, Debug, Default, Clone)]
struct Dropper {
    games_played: Option<usize>,
    map_stats: Option<HashMap<String, DropperMapStat>>,
    maps_completed: Option<usize>,
    fails: Option<usize>,
    fastest_game: Option<usize>,
    games_finished: Option<usize>,
}

#[derive(Deserialize, Debug, Default, Clone)]
struct DropperMapStat {
    best_time: Option<usize>,
    completions: Option<usize>,
}